apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scale-api
  template:
    metadata:
      labels:
        app: scale-api
    spec:
      containers:
        - name: scale-api
          image: manishchhetri01/scaleapi:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: mongodb-uri
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
